### ISSUE TITLE
Low share/minute ratio

### ISSUE THREAD

**Issue by Leonardiae** [VeriBlock/ProgPoW-miner#4]
How does this share system work? I don't see much shares submitted in the miner and when it does then it looks like I'm the one who found the block. I never see someone else having a share in that same round. 

I was expecting to have at least one or a few share per minute to qualify for a portion of the block reward of the latest round but now it does not seem to work like that.

It looks to me that no shares are submitted, only when a block is found is the solution submitted and that's the share.

**Comment by overcookedpanda** [comment]
Due to the low initial difficulty of the network and the pool's minimum share difficulty, you will see 1 share per block/round until network difficulty reaches 4.26G per @max-sanchez

**Comment by Leonardiae** [comment]
Yep I have indeed seen multiple shares per round when network difficulty is higher than 4.26G. Thanks.
